### ISSUE TITLE
feature req: ability to upload pictures on to posts

### ISSUE THREAD

**Issue by sindhus** [hackerschool/community#126]
one use case on why this would be useful:

people should be able to add pictures of their recommends for cheap eats especially if they are indicating carts, that can be hard to find. https://community.hackerschool.com/t/cheap-eats/31

**Comment by zachallaun** [comment]
I don't believe we're going to add this – I'd recommend that people use other image-hosting services and then link the images using the `![](www.image-hosting.com/my-image.png)` markdown syntax.
