### ISSUE TITLE
There are at least five different types of postings likely to appear on Community

### ISSUE THREAD

**Issue by brannerchinese** [hackerschool/community#152]
I can think of five different kinds of information that are likely to appear on Hacker School Community, and I suggest that they be handled in different ways. Two of them I think are likely to clutter the Community and should be posted using a different tool
 1. **Current announcements** that have a definite or likely expiration date after which they don't need to be seen any more (except for archival purposes). Note that some of these may include a date other than the posting-date, which would be useful to highlight somehow.
   - Examples: upcoming events, Regions.
   - Expiration date: yes; archive afterwards.
   - Order of later replies to original post: comments should follow original post; original post is the main item of interest.
 1. **Lists of short-term opportunities**. I think a **bulletin-board format would be better** than the Community here.
   - Examples: housing available, jobs available.
   - Expiration date: yes; perhaps no need even to archive afterwards.
   - Order of later replies to original post: ideally, newer replies should go to the top because there isn't normally a conversation going on — in most cases every newer reply is a discrete opportunity, so freshness is the key issue, rather than a sequence to be read through in order. 
 1. **Reference**: information and recommendations that may be useful for the long term and should not expire or cease to be visible. 
   - Examples: shopping recommendations, tips for finding housing, visas, banking, cellphones, software and book discounts, "Add yourself to the HS map", announcement of the start of "Code Words".
   - Expiration date: usually not, though some editing and coalescence may be useful over time. 
   - Order of later replies to original post: comments below original post; original post at top. 
 1. **Questions about technical subjects**. There's no telling after how long these should cease to be regularly visible, because people may continue to contribute over the very long time. Posts of this sort sometimes benefit from being edited down for future reference. 
   - Examples: Programming.
   - Expiration date: no; these are important to have visible for the long term. But not on a wiki, where the original content can be wrongly edited by any hand.
   - Order of later replies to original post: answers below question; question at top. 
 1. **Conversations**. These generally go on much longer than actual questions about technical subjects — even though they may be about technical matters — but are less likely to have a concrete question and answer. I think a **chat client like Zulip is the best venue** for these — better than the Community.

[end]

**Comment by zachallaun** [comment]
I'm going to close this for now since we've all had some time to use Community and to see how it fits in. If you have specific suggestions for fixes/changes, please feel free to open new issues or start a new discussion in the [Meta subforum](https://community.hackerschool.com/f/meta/8).
