### ISSUE TITLE
iOS web login got http 500 error

### ISSUE THREAD

**Issue by plredmond** [hackerschool/community#208]
### context

Chrome browser on an iPhone4 running the latest iOS 7 Successfully repro'd 2 of 2 tries yesterday and today, once using a normal tab and once using an incognito tab. I observed the **500 error, which is probably associated with a traceback somewhere in your logs**, at two specific times. This may help you track it down.

* Sept 6 2014, 1:21pm PDT
* Sept 7 2014, 10:24pm PDT

### repro

1. Navigate to community.hackerschool.com
1. Be redirected to hacker school oath login page
1. Enter email/password and hit "Done" (email was entered with capital first letter)
1. Get attached 500 error (see below)

### screenshot

![img_2627](https://cloud.githubusercontent.com/assets/1078772/4181399/2e12b3cc-3718-11e4-93ec-8df30ea32d55.jpg)

**Comment by zachallaun** [comment]
We've not been able to reproduce this. It seems to have been an issue with hackerschool.com, not community.hackerschool.com, so I'm going to close this issue and keep an eye on possible future oauth issues.
