### ISSUE TITLE
Add friction to Everyone broadcasting

### ISSUE THREAD

**Issue by FiloSottile** [hackerschool/community#244]
I feel like Community is doing a good job of separating the threads into Subforums (areas, General...) and subscribe-to-Subforum works, so I think it should be harder to broadcast to Everyone.

What I'm suggesting is a confirm dialog asking to confirm that the user really wants to do that.

Honestly I feel like sometimes "Broadcast to Everyone" is mistaken for "Broadcast to everyone in the Subforum", whereas that always happen anyway, right? It might be specified in the dialog.

**Comment by zachallaun** [comment]
Going to close this. It hasn't been an issue in practice and we have some changes in store for broadcast groups that should reduce confusion.
