### ISSUE TITLE
@-mentioning some people doesn't get highlighted by UI

### ISSUE THREAD

**Issue by plredmond** [hackerschool/community#282]
I @-mentioned J.J. in [this thread](https://community.hackerschool.com/t/hacker-school-as-a-consultancycontractor-network/265) using Community's naming auto-complete feature, but the mention doesn't seem to have taken effect in my post, possibly because of the parentheses in is name.

![screen shot 2015-01-19 at 4 03 14 pm](https://cloud.githubusercontent.com/assets/1078772/5810036/b5e7f812-9ff4-11e4-8a6c-46cf0c9b23bd.png)

**Comment by zachallaun** [comment]
Thanks @plredmond. You were right, the problem is that we were transforming names into regular expressions without escaping special chars like `()`. Fix should be deployed soon.

**Comment by plredmond** [comment]
Woo! Yay it's fixed!
