### ISSUE TITLE
Receiving emails from sub forum I'm not subscribed to.

### ISSUE THREAD

**Issue by oskarth** [hackerschool/community#286]
For example:

```
from:	XXX <YYY>
reply-to:	Community <reply-v2--423-3541--a99b323bc0046bd6200b1c7c4c23841ff6a6ead9@mail.community.hackerschool.com>
to:	me@oskarth.com
date:	Mon, Jan 26, 2015 at 6:02 PM
subject:	[Community - New York] ZZZ
mailing list:	new-york.community.hackerschool.com Filter messages from this mailing list
mailed-by:	mail.community.hackerschool.com
signed-by:	mail.community.hackerschool.com
```

In Community:

```
You are not receiving emails because you have unsubscribed.
```
(https://community.hackerschool.com/f/new-york/5)

**Comment by zachallaun** [comment]
Are you unsubscribed from both the subforum and the thread? If you're unsubscribed from the subforum you won't receive emails when new threads are created, but you would still receive emails when new posts are made to threads to which you're subscribed. (If that makes sense.)

**Comment by zachallaun** [comment]
You can check that you're unsubscribed from the thread by visiting it on Community and looking for the same status indicator at the top. If you are in fact unsubscribed, will you please privately ping me a link to the exact thread you're still receiving emails for?

**Comment by oskarth** [comment]
Indeed:

```
You are receiving emails because you were subscribed to this thread's subforum.
```

I haven't interacted with the thread (no posting, no manual subscribe), but I assume the thread is from before I unsubscribed from the sub forum. Not sure if this is the desired behavior or not. Anyway, resolved on my end - thanks!

**Comment by zachallaun** [comment]
Yep– this is currently the "correct" behavior, though I don't think it's actually desired =). Right now we don't keep track of threads that you were subscribed to automatically, but we plan to start doing so so that we can unsubscribe you in exactly this situation. Sorry for the confusion!
